=== OnezPH-Dev/Community-Dog-Lost-and-Found-XML-based-system/dogs.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dogs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dog" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="photo" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="contact" type="xs:string"/>
                            <xs:element name="reward" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== OnezPH-Dev/Community-Dog-Lost-and-Found-XML-based-system/dogs.xml
<?xml version="1.0"?>
<dogs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dogs.xsd">
<dog><name>John Smith</name><contact>(555) 123-4567</contact><reward>12325</reward><photo>img1.jpg</photo></dog><dog><name>Emily Johnson</name><contact>(555) 234-5678</contact><reward>56457576</reward><photo>img1.jpg</photo></dog><dog><name>Michael Brown</name><contact>(555) 345-6789</contact><reward>456457567</reward><photo>img1.jpg</photo></dog><dog><name>Sarah Davis</name><contact>(555) 456-7890</contact><reward>5365764</reward><photo>img1.jpg</photo></dog><dog><name>David Wilson</name><contact>(555) 567-8901</contact><reward>5678756453qqe</reward><photo>img1.jpg</photo></dog><dog><name> Amanda Thomas</name><contact>(555) 890-1234</contact><reward>345345</reward><photo>img1.jpg</photo></dog><dog><name>Laura Clark</name><contact>(555) 234-5679</contact><reward>345346356546</reward><photo>img1.jpg</photo></dog><dog><name>Megan White</name><contact>(555) 012-3456</contact><reward>545y56</reward><photo>Descargar lindo, golden retriever, cachorro, agitar, pata, caricatura gratis.jpg</photo></dog><dog><name>zeno</name><contact>(555) 345-6789</contact><reward>345646747</reward><photo>img1.jpg</photo></dog><dog><name>zen zen</name><contact>56748634563</contact><reward>2345345</reward><photo>maltese-portrait.jpg</photo></dog><dog><name>night night</name><contact>43563</contact><reward>3457367</reward><photo>img1.jpg</photo></dog></dogs>
